### ISSUE TITLE
pipeline failed at annotation_grouping_pre_consensus :igblast

### ISSUE THREAD

**Issue by jagos01** [kzeglinski/nabseq_nf#2]
Hello, 
I am trying to run this workflow on my local computer.  I used the following command:
nextflow run ./nabseq_nf/main.nf --fastq_dir /home/scott/Data_Raw/mAbs_June1/20230601_1623_MC-111382_FAW58338_807354c1/fastq_pass/ --organism mouse --sample_sheet /home/scott/Data_Analysis/mAb_test/sample_sheet.csv -profile standard

I received the following error message: 

Command error:
  BLAST query/options error: Germline annotation database mouse/mouse_V could not be found in [internal_data] directory
  Please refer to the BLAST+ user manual.

Any help resolving this is appreciated.
Thanks,
Scott

**Comment by kzeglinski** [comment]
Hi Scott!

A couple of things here:
1. If you are running the latest version of NAb-seq, we now require the organism to be specified in the sample sheet rather than as a command line parameter (sorry for the confusion! I should probably add an error message flagging this change). We made this change to allow the running of a batch of samples from different organisms at once.
So the sample sheet should look like:
barcode,sample_name,species,report_group
barcode18,15-14-7H9-19-1,mouse,1
For more information please see the tutorial: https://kzeglinski.github.io/nab-seq/new_tutorial.html

2. The error message you're receiving I think probably relates to file mounting in containers. I believe that -profile standard in nextflow usually uses docker. In this case, you might want to add the following to the docker section of the nextflow config: `runOptions= "-v $HOME:$HOME"` (or you can replace $HOME with the path of where the nabseq_nf folder is located). I'm not sure why nextflow doesn't mount these paths automatically, but a few people have had this issue now so I might add a note in the documentation on it.

Hopefully this helps! Happy to answer any questions & help troubleshoot further if needed ☺️

**Comment by jagos01** [comment]
Hello,
Thank you for your quick reply.  I removed the organism from the command line (sample sheet was formatted correctly) and added the docker mount path in nexflow config.  Works perfectly now.
Thanks again,
Scott

**Comment by kzeglinski** [comment]
No worries! Glad to hear it is working 😄
